apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mlops-staging
resources:
  - ../../../k8s/deployment-cpu.yaml
  - ../../../k8s/service-cpu.yaml
patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: mlops-fraud-api